// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJIV9mlVfkdkw4R2ivE8uKuZDZ7pfV5OM',
    appId: '1:750336672335:web:cc3d229bbb679ec4e8203a',
    messagingSenderId: '750336672335',
    projectId: 'testkaraworkshop',
    authDomain: 'testkaraworkshop.firebaseapp.com',
    storageBucket: 'testkaraworkshop.appspot.com',
    measurementId: 'G-0WC021PGE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnD40AVxF4yPeO8DII6DoW_An3Y8bvwUc',
    appId: '1:750336672335:android:6f9fdd727a2041f9e8203a',
    messagingSenderId: '750336672335',
    projectId: 'testkaraworkshop',
    storageBucket: 'testkaraworkshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtfbtmnkkoZgLkGEebPQNKX1AJZ3_uZP0',
    appId: '1:750336672335:ios:d9c8e2a625d2c8ade8203a',
    messagingSenderId: '750336672335',
    projectId: 'testkaraworkshop',
    storageBucket: 'testkaraworkshop.appspot.com',
    iosClientId: '750336672335-ten9e1c7dccd6f1dbldfnl7ns5tf0qh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.karaWorkshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtfbtmnkkoZgLkGEebPQNKX1AJZ3_uZP0',
    appId: '1:750336672335:ios:d064fa4447f9a112e8203a',
    messagingSenderId: '750336672335',
    projectId: 'testkaraworkshop',
    storageBucket: 'testkaraworkshop.appspot.com',
    iosClientId: '750336672335-4tasl3aa6phk7o17lij62ek04cvtcvof.apps.googleusercontent.com',
    iosBundleId: 'com.example.karaWorkshop.RunnerTests',
  );
}
